# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CS4S Maths @ UON
email: daniel.hickmott@uon.edu.au
contact: Daniel Hickmott
baseurl: "/math-2017"

# Content Pages Paths
resources_path: "/resources"
extras_path: "/extras"

# Day 1 Paths
day1_path: "/day1/"
network_concepts_path: "/day1/network_concepts"
msts_path: "/day1/msts"
coding_path: "/day1/coding"

# Day 2 Paths
day2_path: "/day2/"
networks_in_edgy_path: "/day2/networks_in_edgy"
msts_in_edgy_path: "/day2/msts_in_edgy"
blocks_to_text_path: "/day2/blocks_to_text"

# Build settings
markdown: kramdown
